"""Added refreshtoken model

Revision ID: 0c08bf06c99d
Revises: 12e650d28837
Create Date: 2022-03-16 12:12:06.330244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c08bf06c99d'
down_revision = '0a1545da68fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshToken',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('deviceId', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('expiresOn', sa.DateTime(), nullable=False),
    sa.Column('revokedOn', sa.DateTime(), nullable=True),
    sa.Column('replacedByToken', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['client.id'], ),
    sa.PrimaryKeyConstraint('token'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refreshToken')
    # ### end Alembic commands ###
