name: Development

on: [pull_request, workflow_call]

jobs:
  tox:
    name: format, lint and test.
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: check out repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.8"
      - name: Load cache (if exists)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Install Dependancies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[dev]
      - name: Run Tox
        run: tox
